name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Read version from package.json
      run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Versão detectada: $VERSION"

    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/ci:$VERSION .
      env:
          VERSION: ${{ env.VERSION }}
    - name: Push the Docker image to repository
      run: |
       docker login -u ${{secrets.DOCKER_USER}} -P | ${{secrets.DOCKER_TOKEN}}
       docker push ${{secrets.DOCKER_USER}}/ci:$VERSION

